package base;

public enum PlatForm {
	SELENIUM_LOCAL_CHROME,
	SELENIUM_REMOTE_CHROME,
	SELENIUM_LOCAL_FIREFOX,
	SELENIUM_REMOTE_FIREFOX,	
	APPIUM_ANDROID_APPLICATION,
	APPIUM_IOS_APPLICATION,
	APPIUM_ANDROID_CHROME,
	APPIUM_IOS_SAFARI
}
